### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by bram-abe** [muxinc/strapi-plugin-mux-video-uploader#16]
I know Mux API has an API for developer to be able doing some feature like I mention below. 
But it would be nice if strapi-plugin-mux-video-uploader could natively handle it.

**Feature request**
1. playback_policy option between public & signed.
2. upload text track for subtitle, language_code and subtitle name.

Thanks

**Comment by pavolhudran** [comment]
We are working on yoga platform where we want to sell videos for our customers, we can't sell without this functionality.

**Comment by erikpena** [comment]
Thank you for this @bram-abe, I added this to our Feature Requests board.  We wanted to first release our new design paradigm before adding more functionality.  We've since done this and so we'll be able to prioritize in due time.
