### ISSUE TITLE
Mux settings not showing in Strapi v3.2.5

### ISSUE THREAD

**Issue by heyjaypray** [muxinc/strapi-plugin-mux-video-uploader#2]
Settings fo Mux are not available in the newest strapi version.  Mux assets and permissions however are still showing.

<img width="1676" alt="Screen Shot 2020-10-23 at 6 47 22 PM" src="https://user-images.githubusercontent.com/25106794/97060066-498db700-1560-11eb-8eb4-9c292c0e69c8.png">

edit: it works when downgrading Strapi to 3.1.4 - however with subsequent future releases may be wise to upgrade this feature.  Not sure how much work will have to go into it - but i may make a PR in the future.

**Comment by erikpena** [comment]
Hey @heyjaypray,
Thanks for this.  I actually have an update coming soon which will enable for Strapi v3.3.3.  Hang tight!

**Comment by erikpena** [comment]
Just updated to v1.1.1 which includes this update.
