### ISSUE TITLE
Error while changing settings (keys and secrets)

### ISSUE THREAD

**Issue by brnkmnn** [muxinc/strapi-plugin-mux-video-uploader#3]
While setting the 3 settings there is an error:
`
[2020-11-10T18:02:11.052Z] debug GET /mux-video-uploader/mux-settings (1 ms) 401
[2020-11-10T18:02:27.691Z] debug POST /mux-video-uploader/mux-settings (1 ms) 401
`
I have the public rights set for `muxwebhookhandler`.

**Comment by brnkmnn** [comment]
Update: In admin/src/services/strapi/index.ts the jwt token is retrieved from the session storage. But it is NOT in the session storage, but in the local storage. Manually copying the token to the session storage aswell solves the problem for now, but only for my computer and session.

**Comment by erikpena** [comment]
Hey @brnkmnn,
Thanks for the sleuthing.  I didn't realize that the JWT could be stored in local storage.  Let me speak with the Strapi team to see if there is a better method for obtaining this.

**Comment by erikpena** [comment]
Just updated to v1.1.1 which includes this fix.
