### ISSUE TITLE
Possible wrong data persisted on upload?

### ISSUE THREAD

**Issue by lordjim666** [muxinc/strapi-plugin-mux-video-uploader#31]
Hi,

when I upload video via directUpload only 'title' and 'upload_id' is persisted (asset and playback ids are null) and in this case while upload_id is populated it does no correspond to any asset id in mux.

when I upload video via remoteUpload then only 'title' and 'asset_id' is persisted and the rest is null - in this case asset_id is correct

Strapi: 4.0.5
Plugin: 2.1.1

Assets are correctly uploaded into mux, just strapi can't show them since data are wrong/missing

Am I missing something?

**Comment by erikpena** [comment]
Hello @lordjim666,
Thank you for filing this, it sounds like webhooks has not been set up which is needed to update the fields as videos are getting processed within Mux.

If you're working with an instance of Strapi that is available on the public internet (as in, available that Mux can reach it via a url), then take a look at the [Webhooks](https://github.com/muxinc/strapi-plugin-mux-video-uploader#-webhooks) section of our documentation to see how to configure webhooks.

If you're working with a local instance of Strapi that is not available on the public internet, you can still use this plugin, you'll just need to use something called a "Webhook Relay" to have webhook events forwarded to your Strapi instance.  Take a look at this item in our [FAQ](https://github.com/muxinc/strapi-plugin-mux-video-uploader#my-strapi-instance-is-not-publicly-available-can-i-still-use-webhooks) section.

Thanks!
