### ISSUE TITLE
Include aspect_ratio and duration as available properties.

### ISSUE THREAD

**Issue by twobyte** [muxinc/strapi-plugin-mux-video-uploader#33]
The API exposes aspect_ratio and duration asset data: 
https://docs.mux.com/api-reference/video#tag/assets

Can we include it in the Strapi data graph?
https://github.com/muxinc/strapi-plugin-mux-video-uploader/blob/master/server/controllers/mux.ts#L48-L51

**Comment by erikpena** [comment]
Hello @twobyte,
I don't see why not.  Those two in particular seem pretty reasonable.  I'll create a PR to include this.

**Comment by erikpena** [comment]
Tracked in PR: https://github.com/muxinc/strapi-plugin-mux-video-uploader/pull/36

**Comment by twobyte** [comment]
Great, thanks @erikpena. I look forward to seeing this merged!

**Comment by erikpena** [comment]
Hey @twobyte, this has been merged and published on npmjs.  Give it a spin and let me know how you get along.

Thanks!

**Comment by twobyte** [comment]
Thanks @erikpena, appears to be working well.
