### ISSUE TITLE
Preview-Player not working in Firefox

### ISSUE THREAD

**Issue by sevbauer** [muxinc/strapi-plugin-mux-video-uploader#43]
Hi, thanks for the plugin!

we've encountered a problem with the preview-player in Firefox and on our deployment on AWS S3...

### Expected Behavior
The uploaded video should be playable in the preview-player after clicking on a video in the "Mux Video Uploader"-Library in Strapi.

#### Local
Locally the preview-player works in Chrome, but Firefox displays an "Error".

![image](https://user-images.githubusercontent.com/51238101/183240719-783356f1-bdf5-4927-a8ce-1d3283436330.png)

The Stacktrace leads to parts of the code like that:
![image](https://user-images.githubusercontent.com/51238101/183242008-fc399f21-3b0e-401e-9512-521309acccfc.png)

We could find 4 possible error-messages:
- "no demux matching with content found"
- "Found "+ee+" TS packet/s that do not start with 0x47"
- "fail allocating video mdat "
- "fail allocating audio mdat "

#### Deployment
When deploying the Strapi-Admin to AWS S3 and the backend to an EC2-server (so when doing a splitted frontend/backend-deployment), the video-player doesn't work in Chrome either.

![image](https://user-images.githubusercontent.com/51238101/183241271-609b4ff7-b015-4f78-af06-40c6c3d4344e.png)

Even though the errors look different, we think there's the same root cause.

### Possible Solution
We've tried the following:
As you can see in the first image above (Firefox), there are some CSP-errors (sorry, it's in German). The errors say, that in Firefox inline-scripts are not allowed. That's why we added the following configuration to Strapi's `middleware.js`:
```
  // ...
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "script-src": ["'self'", "'unsafe-inline'"],
          "connect-src": ["'self'", "https:"],

          // etc.

          upgradeInsecureRequests: null,
        },
      },
    },
  },
```

Now the first two errors in Firefox are gone, but it still doesn't work. (Chrome still works)

Another error says that `blob:....` is blocked:
![image](https://user-images.githubusercontent.com/51238101/183241608-7d81757a-a6c9-4077-ac4f-ab3e925f3001.png)

So we changed the middleware-configuration to this:
```
  // ....
  "script-src": ["'self'", "'unsafe-inline'", "blob:"],
  // ....
```

After that all CSP-errors are gone, but the playback doesn't work in Firefox and now also in Chrome!
Also the `MediaError` changes:
![image](https://user-images.githubusercontent.com/51238101/183242187-06894f43-0c68-4d64-9398-2319db80b138.png)

We've searched the code and figured out, that `x` in the error is `console` [here](https://github.com/video-dev/hls.js/blob/8f1384e34d35c7dd2f11ad51bf6a94ae6d62a471/src/remux/mp4-remuxer.ts#L649).

So `console` is `undefined`.

After further research, we somehow found [this issue](https://github.com/video-dev/hls.js/issues/187). I can't remember how we got there and I don't know if it helps.

There our research ended...

### Environment
- A fresh Strapi 4.3.2 project
- strapi-plugin-mux-video-uploader 2.3.0

**Comment by mmcc** [comment]
So sorry about the radio silence on this one. It's been > a year, did you ever figure this out? Going to close it since this is so old (and a few minor versions ago), but ping this thread if you're still seeing it.

**Comment by sevbauer** [comment]
Don't worry, everything is fine. We have adapted to the situation. With our automation fully optimized, frequent checks of the videos in Strapi are no longer necessary.
Maybe I'll find some time to recheck this issue. Thank you!
