### ISSUE TITLE
PUT API not working for MUX assets collection

### ISSUE THREAD

**Issue by aagamLF** [muxinc/strapi-plugin-mux-video-uploader#44]
Hi,

We have encountered an issue with the PUT API call to update MUX asset collection. The API response is 200 OK but the corresponding record is not getting updated as expected.

**API cURL**
curl --location --request PUT 'https://{hosted-strapi-URL}/mux-video-uploader/mux-asset/22' \
--header 'Authorization: Bearer ey....' \
--header 'Content-Type: application/json' \
--data-raw '{
    "initUploadFacility": 10
}'

**Expected Response**
_initUploadFacility_  updated to 10

{
    "id": 22,
    "title": "Video 1",
    "upload_id": "ns4m....",
    "asset_id": "tc6k...",
    "playback_id": "mj6e...",
    "error_message": null,
    "isReady": true,
    "maxStoredResolution": null,
    "maxStoredFrameRate": null,
    "aspectRatio": "16:9",
    "maxWidth": null,
    "maxHeight": null,
    "initUploadFacility": 10,
    "createdAt": "2022-08-03T17:03:04.076Z",
    "updatedAt": "2022-08-05T15:26:10.285Z",
    "duration": 500.0
}

**Actual Response**
_initUploadFacility_ still remains null
{
    "id": 22,
    "title": "Video 1",
    "upload_id": "ns4m....",
    "asset_id": "tc6k...",
    "playback_id": "mj6e...",
    "error_message": null,
    "isReady": true,
    "maxStoredResolution": null,
    "maxStoredFrameRate": null,
    "aspectRatio": "16:9",
    "maxWidth": null,
    "maxHeight": null,
    "initUploadFacility": null,
    "createdAt": "2022-08-03T17:03:04.076Z",
    "updatedAt": "2022-08-05T15:26:10.285Z",
    "duration": 500.0
}

New data points have been added to the default MUX assets collection as shown below:

![image](https://user-images.githubusercontent.com/101893340/183757291-e335dc93-5aa6-4ba8-a211-69576e96f24b.png)

**Environment**
- Strapi v4.1.11
- strapi-plugin-mux-video-uploader v2.2.1

**Comment by erikpena** [comment]
Hello @aagamLF, great to hear from you again!  Based on this issue, we would not want to introduce a change to look for non-native fields to the mux-asset collection type.

For what it's worth, I understand what you're trying to do (extend the metadata for mux-asset).  I think if I were to make any sort of recommendation for a workaround, it would be to **not** change the mux-asset collection type.  Rather, create a new collection type that has a relationship to mux-asset and that includes the new metadata you're interested in setting.  This effectively wraps the mux-asset collection type with a new collection type that contains _whatever_ you want.

Let me know if any of this is unclear and we can talk further about the above and assist in collaborating on a resolution.  Thank you!
