### ISSUE TITLE
Cannot give Editor Role permission to upload, view or manage videos.

### ISSUE THREAD

**Issue by twobyte** [muxinc/strapi-plugin-mux-video-uploader#45]
This seems like a massive oversight! 

The Editor role is described as so:

“Editors can manage and publish contents including those of other users.”

And yet, they cannot access the Mux Video Uploader admin panel. It is not possible to enable access either, as the checkboxes are disabled.

![Screenshot 2022-09-05 at 15 10 58](https://user-images.githubusercontent.com/971319/188469317-272cf37c-527c-437e-9c47-e2fa6cb065ed.png)

The Upload Plugins permissions are enabled for the Editor, so why not the video uploader as well?

**Comment by erikpena** [comment]
Thank you for filing this @twobyte.  We will take a look at prioritizing this.

**Comment by erikpena** [comment]
Hey @twobyte, after reviewing this, it turns out that the ability to use the "Select all" is based on having a Strapi Enterprise license.  So this is intended behavior.  Apologies for taking a while to get to this, but I was only recently able to secure an Enterprise license for testing.

**Comment by twobyte** [comment]
OK, thanks @erikpena. Quite disappointed with Strapi, feels a bit bait and switch....
