### ISSUE TITLE
Limit playback duration

### ISSUE THREAD

**Issue by websnooze** [muxinc/strapi-plugin-mux-video-uploader#64]
Hi, Is there a way of limiting the listening/streaming time for an audio file to X seconds (e.g. 30s)?

**Comment by erikpena** [comment]
Hello @mathiaslac,
There currently is not a way to do this with the plugin.  Can you share what the use case is for this?  What are you trying to achieve and how will it be used in your particular application?  The more information I can get about this, the better I can help guide on possible approaches.

Thank you,

**Comment by mathiaslac** [comment]
Hi @erikpena 
My Webapp is built for an independant music label, that provide to public users, short preview to music from label artists's...
so I want to set preview time to 30s or 25s like on iTunes and give full sound listening time to premium users

**Comment by mmcc** [comment]
Unfortunately we don't have a great way of doing that on the Mux side of things. You could do some things to secure the playback overall, but any playback _duration_ limitations would be purely client side. i.e., You could do things to limit who can stream something at all, but we don't have a way of saying "only stream the first 30 seconds."

If you're ok with that path then you'd need to do that outside of this plugin.
