### ISSUE TITLE
app with latest strapi and mux does not build

### ISSUE THREAD

**Issue by SergeiLebedev** [muxinc/strapi-plugin-mux-video-uploader#67]
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in '/Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/admin/src'
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/Compilation.js:2022:28
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'react-dom/client' in '/Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/admin/src'
  Parsed request is a module
  using description file: /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/admin/src/node_modules doesn't exist or is not a directory
      /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/admin/node_modules doesn't exist or is not a directory
      /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules
        existing directory /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom
          using description file: /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/package.json (relative path: .)
            using description file: /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/package.json (relative path: ./client)
              no extension
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client doesn't exist
              .js
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client.js doesn't exist
              .jsx
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client.jsx doesn't exist
              .react.js
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client.react.js doesn't exist
              .ts
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client.ts doesn't exist
              .tsx
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client.tsx doesn't exist
              as directory
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client doesn't exist
      /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/node_modules doesn't exist or is not a directory
      /Users/sergeilebedev/AmazingFactsProjects/node_modules doesn't exist or is not a directory
      /Users/sergeilebedev/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in '/Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/admin/src'
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/Compilation.js:2022:28
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'react-dom/client' in '/Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/admin/src'
  Parsed request is a module
  using description file: /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/admin/src/node_modules doesn't exist or is not a directory
      /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/admin/node_modules doesn't exist or is not a directory
      /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules
        existing directory /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom
          using description file: /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/package.json (relative path: .)
            using description file: /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/package.json (relative path: ./client)
              no extension
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client doesn't exist
              .js
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client.js doesn't exist
              .jsx
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client.jsx doesn't exist
              .react.js
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client.react.js doesn't exist
              .ts
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client.ts doesn't exist
              .tsx
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client.tsx doesn't exist
              as directory
                /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/amazing-facts-strapi/node_modules/react-dom/client doesn't exist
      /Users/sergeilebedev/AmazingFactsProjects/DigitalOceanDeploy/node_modules doesn't exist or is not a directory
      /Users/sergeilebedev/AmazingFactsProjects/node_modules doesn't exist or is not a directory
      /Users/sergeilebedev/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
error Command failed with exit code 1.

**Comment by cjpillsbury** [comment]
Hey @SergeiLebedev from your console dump ☝️, it doesn't look like this is related to Mux Video? I'm seeing some references to cache with "amazing-facts-strapi". Have you tried blowing away any cached build files and installing/building from scratch?

**Comment by SergeiLebedevJobAdder** [comment]
The problem was that mux uses lower version of React when the latest strapi uses higher version. When I downgrade Strapi version it started to work. But It does not work with latest strapi version.

**Comment by alexpmichelet** [comment]
Hi @SergeiLebedevJobAdder , could you share the version of strapi that worked for you? Thanks!

**Comment by SergeiLebedevJobAdder** [comment]
"@strapi/strapi": "4.12.7",

**Comment by erikpena** [comment]
Closing due to staleness of the issue.  This should no longer be an issue in the latest version of Strapi and the strapi-plugin-mux-video-uploader.
