### ISSUE TITLE
Subtitle / closed caption support?

### ISSUE THREAD

**Issue by kelihansen** [muxinc/strapi-plugin-mux-video-uploader#68]
Hi! Are there any plans to make it possible to select both a video file and - for example - an SRT file when using the Mux uploader? 🙏

**Comment by erikpena** [comment]
Hello @kelihansen,
We are actually getting ready to add this feature into the plugin.  However, there will be a few caveats to this:

- Mux currently does not support direct uploads for SRT/VTTfiles.  This means that you'll need to have these files hosted somewhere publicly.
- We will implement a modal that will allow you to specify the URL for the SRT/VTT file where Mux will pull the file from.
- We are also evaluating doing the same thing for our new [Multi Track Audio](https://docs.mux.com/guides/video/add-alternate-audio-tracks-to-your-videos) support where users can specify a URL for additional audio tracks.

**Comment by kelihansen** [comment]
That's exciting - thanks for the details!

**Comment by kelihansen** [comment]
@erikpena Are we talking, like, next week? Next month? Next year? 😄

**Comment by erikpena** [comment]
![image](https://github.com/muxinc/strapi-plugin-mux-video-uploader/assets/2187347/3b388f61-64a8-4f2f-8c37-1dc639c95187)

I think given that I'm going to be breaking into this and working on a couple of other things that are now popping up, the best bet is a ~month timeline.  Subject to change and all that but I will be striving to get this out sooner.

**Comment by drewfead** [comment]
Is there any update on this? We're really interested in this feature. Is there a suggested workaround in the interim?
