### ISSUE TITLE
Request: Allow us to delete

### ISSUE THREAD

**Issue by johnark88** [muxinc/strapi-plugin-mux-video-uploader#69]
`Issue:`  No delete functionality
`Reproduce:`
Install Mux on fresh install
setup token id/secret, setup webhook with ngrok and get webhook secret - in Mux dashboard.
Add tokens and id's to strapi settings config in the strapi admin
Upload asset via `Mux Video Uploader`
Click delete icon then click confirm. 
Nothing happens, no console log and no strapi server log output.  

Upon inspection it looks like the function behind the confirm button is empty..... 
*EDIT* 
Its possible the modal maybe closing too quickly for the function to fire, not even the before/after delete lifecycles are firing. 

Any advice or help would be greatly appreciated. Thank you!

**Comment by johnark88** [comment]
See PR #70 for fix

**Comment by cjpillsbury** [comment]
Hey @johnark88 ! Thanks for filing the issue and the PR! Let me see if someone with a bit more context has the bandwidth for a PR review.

**Comment by kelihansen** [comment]
I would also love to see this fixed!

**Comment by erikpena** [comment]
This issue should no longer be a problem.  Please re-ppen if you experience the issue again.  Thank you!
