### ISSUE TITLE
npm can't install strapi-plugin-mux-video-uploader@1.1.1 

### ISSUE THREAD

**Issue by bram-abe** [muxinc/strapi-plugin-mux-video-uploader#7]
I found the log in terminal when I do "npm i strapi-plugin-mux-video-uploader"  it still downloaded  strapi-plugin-mux-video-uploader@1.1.0 , not the latest version 1.1.1.
if I change  strapi-plugin-mux-video-uploader in package.json to 1.1.1 then I got an error below:

> npm ERR! code ETARGET
npm ERR! notarget No matching version found for strapi-plugin-mux-video-uploader@1.1.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

hai @erikpena waiting for your answer. thx

_Originally posted by @bram-abe in https://github.com/muxinc/strapi-plugin-mux-video-uploader/issues/6#issuecomment-803594423_

**Comment by bram-abe** [comment]
it seems v1.1.1 not already in npm registry, thats why npm can't see the match version as stated in package.json.
set npm to download from git repo instead of npm registry solve the problem.

`"strapi-plugin-mux-video-uploader": "git+https://github.com/muxinc/strapi-plugin-mux-video-uploader.git"`

**Comment by erikpena** [comment]
Thanks for this heads up @bram-abe, we have a release coming and I'll be sure to cut a release for npm for this :)

**Comment by erikpena** [comment]
Quick update @bram-abe—

I just published v1.1.1 so that npm has a record of this version number.  However, as previously mentioned, we are going to be creating another release here soon (1.2.0) that will bring support for Strapi 3.6.2.

**Comment by bram-abe** [comment]
> 
> 
> Quick update @bram-abe—
> 
> I just published v1.1.1 so that npm has a record of this version number. However, as previously mentioned, we are going to be creating another release here soon (1.2.0) that will bring support for Strapi 3.6.2.

waiting for that, thx @erikpena

**Comment by erikpena** [comment]
Hey @bram-abe,
Just wanted to let you know that we released a new version of this plugin (1.2.0) which supports Strapi 3.6.2—

https://github.com/muxinc/strapi-plugin-mux-video-uploader/releases/tag/v1.2.0

I'm going to be closing this issue.  Thank you!
