### ISSUE TITLE
Feature Request: Enable/Disable Auto-Generated Captions

### ISSUE THREAD

**Issue by sracela** [muxinc/strapi-plugin-mux-video-uploader#72]
## Feature Request

**Description:**
Are there any plans to make it possible to enable/disable the new Mux auto-generated captions feature?

[Mux Auto-Generated Captions Feature Documentation](https://docs.mux.com/guides/add-autogenerated-captions-and-use-transcripts#enabling-auto-generated-captions)

I was thinking on something like the screenshot below maybe. 

**Screenshot:**

<img width="610" alt="Screenshot 2023-11-14 at 5 38 00 PM" src="https://github.com/muxinc/strapi-plugin-mux-video-uploader/assets/43761621/41cc5a89-cf94-4506-acf2-88c3cec2fb3b">

**Maybe a even better option would be  a "Enable Auto-generated captions" checkbox field in the Settings page, so it gets enabled or disabled for all videos.**

Taking a look at the code adding the generated_subtitles object here may do the trick:

```
//server/services/mux.js

return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, getMuxClient()];
                        case 1:
                            Video = (_a.sent()).Video;
                            return [2 /*return*/, Video.Uploads.create({
                                cors_origin: corsOrigin,
                                new_asset_settings: {
                                    playback_policy: ['public'],
                                    input: [
                                        {
                                            "generated_subtitles": [
                                                {
                                                    "language_code": "en",
                                                    "name": "English CC"
                                                }
                                            ]
                                        }
                                    ]
                                },
                            })];
                    }
                });
```

**Comment by dylanjha** [comment]
Thank you @sracela ! This is definitely on the road map after recently releasing this feature. In the form we would probably also have to expose a way for the user to enter a `language_code` and `name` for the generated subtitles track.

I was thinking we'd probably want this configuration to exist both globally at the plugin level, but then also the ability to override it for an individual video. Thoughts?

**Comment by kelihansen** [comment]
Yes, please - we'd love this, too!

**Comment by sracela** [comment]
Thanks for repplying @dylanjha ! Yes, but I would not rush on exposing a way for the user to enter a language_code and name, because as mux team points out on their documentation:

> Note that language_code must be en currently; other languages aren't currently supported.

And regarding this:

> I was thinking we'd probably want this configuration to exist both globally at the plugin level, but then also the ability to override it for an individual video. Thoughts?

Sounds perfect, both solutions would work for my team actually! Even a more advanced solution would be to choose between not adding captions, adding them manually or let mux auto-generate them.

Also, I would like to express my interest in working on this feature. Could I receive some guidance on how to proceed? I'm willing to create a PR and discuss the implementation details. If there's any specification I should follow, I'd be happy to adhere to it.

Looking forward to the opportunity to contribute to the project since this plugin has been really helpful for my team.

**Comment by arsedler9** [comment]
Also very interested in this! Has any progress been made?

**Comment by erikpena** [comment]
This feature was rolled out in v2.8.0.  Closing this issue.  Thank you for your input and please let us know if you have any other requests!
