### ISSUE TITLE
Asset is not deleted from Mux Video Uploader plugin delete icon

### ISSUE THREAD

**Issue by aasthag-14** [muxinc/strapi-plugin-mux-video-uploader#73]
Strapi > Mux Video Uploader > Open any asset
<img width="386" alt="image" src="https://github.com/muxinc/strapi-plugin-mux-video-uploader/assets/75171852/118ab164-645e-43ab-997c-c6982ef2f4d1">

Click delete icon from the Video Details modal
<img width="735" alt="image" src="https://github.com/muxinc/strapi-plugin-mux-video-uploader/assets/75171852/fb4360e5-e215-4784-aeab-bbd61cada6bb">

Click Confirm
<img width="731" alt="image" src="https://github.com/muxinc/strapi-plugin-mux-video-uploader/assets/75171852/3feb67ca-1894-4562-90a4-6d569e10d283">

Nothing happens, the asset still shows up in the library

**Comment by erikpena** [comment]
Closing this ticket as it is old and should no longer be an issue.  Please re-open if you experience it again.
