### ISSUE TITLE
Can't add custom caption/subtitle file

### ISSUE THREAD

**Issue by kelihansen** [muxinc/strapi-plugin-mux-video-uploader#78]
Hi! We're so excited to see @hdoro's [features](https://github.com/muxinc/strapi-plugin-mux-video-uploader/pull/75) merged. Auto-generating captions when we upload a new asset appears to be working beautifully.

Unfortunately, uploading a caption file silently fails. I think this is because [`strapi.backendURL`](https://github.com/muxinc/strapi-plugin-mux-video-uploader/blob/master/server/utils/text-tracks.ts#L30) is meant to be used in the browser - it's `undefined` on the server. I'm not 100% sure what value should replace it, maybe `process.env.STRAPI_ADMIN_BACKEND_URL`?

It also appears that, while `Language` and `File` are marked as required when you try to add a file, nothing happens if you hit "Finish" without them.

**Comment by daytime-em** [comment]
Hi! Thanks for your report. We'll investigate and get back to you soon

**Comment by erikpena** [comment]
Hello @kelihansen ,
Thank you for filing this issue.  You are correct in that we _were_ using the `process.env.STRAPI_ADMIN_BACKEND_URL`.  We've just launched a new version of this plugin (v3.0.1) which is targeted to work with Strapi v5 and have made some enhancements on how this all works.  Going forward, you will want to use the `url` config property in the `./config/server.ts` to specify your domain name.  Take a look at the following example which is intended Typescript version of Strapi (note that you'll need to change the obviously exampled url value)—

```
export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  app: {
    keys: env.array('APP_KEYS'),
  },
  url: 'https://YOUR.COOL.DOMAIN.COM'
});
```

Please let us know if you have any further questions.  Thank you!
