### ISSUE TITLE
Strapi 5 compatibility

### ISSUE THREAD

**Issue by CoreyH** [muxinc/strapi-plugin-mux-video-uploader#87]
Has anyone tried Mux with Strapi 5 yet? 

I'm spinning up a brand new instance for a startup project and I figure I might as well jump on 5 while I have no content to migrate, but was planning to use Mux.

**Comment by derrickmehaffy** [comment]
We (Strapi) are working with mux to upgrade their plugin, currently no their latest stable version will not work with strapi 5

**Comment by erikpena** [comment]
Hello @CoreyH and @travismmorgan !
I am pleased to let you know that we've just released a new version of the plugin (v3.0.1) that is compatible with Strapi v5.  As you're doing your upgrade, please note that there is one breaking change with how we handle config of Mux values such as access tokens, signing keys and webhook signing secrets.  To understand how to migrate to the new file based config, please review the `README.md`.

Please reach out if you have any issues and I'll be more than happy to assist.

Thank you!
