### ISSUE TITLE
When can we expect Strapi 5 support?

### ISSUE THREAD

**Issue by anshul-fitsib** [muxinc/strapi-plugin-mux-video-uploader#89]
Can you confirm the target date for the plugin update to support Strapi 5?

**Comment by erikpena** [comment]
Hello @anshul-fitsib!  Thank you for reaching out to us.  I can share that this is currently underway.  I don't have an ETA when it will hit GA but I can definitely let you know as we get more clarity around a timeline!

**Comment by erikpena** [comment]
Hello @anshul-fitsib !
I am pleased to let you know that we've just released a new version of the plugin (v3.0.1) that is compatible with Strapi v5.  As you're doing your upgrade, please note that there is one breaking change with how we handle config of Mux values such as access tokens, signing keys and webhook signing secrets.  To understand how to migrate to the new file based config, please review the `README.md`.

Please reach out if you have any issues and I'll be more than happy to assist.

Thank you!
